"""empty message

Revision ID: 0e511565f194
Revises: 
Create Date: 2022-05-18 23:18:17.428390

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e511565f194'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Administrador',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=80), nullable=False),
    sa.Column('usuario', sa.String(length=200), nullable=False),
    sa.Column('contrasenia', sa.String(length=200), nullable=False),
    sa.Column('estado', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('usuario')
    )
    op.create_table('Estudiante',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=80), nullable=False),
    sa.Column('matricula', sa.String(length=200), nullable=False),
    sa.Column('contrasenia', sa.String(length=200), nullable=False),
    sa.Column('estado', sa.Boolean(), nullable=True),
    sa.Column('licenciatura', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('matricula')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Estudiante')
    op.drop_table('Administrador')
    # ### end Alembic commands ###
