"""empty message

Revision ID: b6f1d1707783
Revises: 
Create Date: 2022-05-22 04:30:40.981856

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b6f1d1707783'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Place',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('address', sa.String(length=500), nullable=False),
    sa.Column('services', sa.String(length=500), nullable=False),
    sa.Column('schedule', sa.String(length=500), nullable=False),
    sa.Column('status', sa.String(length=200), nullable=True),
    sa.Column('type_place', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('Student',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('enrollment', sa.String(length=200), nullable=False),
    sa.Column('password', sa.String(length=200), nullable=False),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.Column('degree', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('enrollment')
    )
    op.create_table('Opinion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student', sa.Integer(), nullable=False),
    sa.Column('date', sa.String(length=200), nullable=False),
    sa.Column('hour', sa.String(length=5), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=False),
    sa.Column('id_place', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_place'], ['Place.id'], ),
    sa.ForeignKeyConstraint(['student'], ['Student.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Opinion')
    op.drop_table('Student')
    op.drop_table('Place')
    # ### end Alembic commands ###
