name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:      
          username: marivs
          password: 7cb9d36d-0e09-4d71-8c05-f8c6ecc2e291
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./VidaForaneaServidor/API
          push: true
          tags: marivs/vidaforanea:latest

           
           
